// Date: 1/7/2013 9:49:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package enhancedbooks.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelFlyingBook extends ModelBase {
    //fields
    ModelRenderer LeftBook;
    ModelRenderer RightBook;
    ModelRenderer Left_Wing;
    ModelRenderer Right_Wing;
    ModelRenderer CenterBook;
    ModelRenderer BackBook;

    public ModelFlyingBook() {
        textureWidth = 64;
        textureHeight = 32;

        LeftBook = new ModelRenderer(this, 0, 0);
        LeftBook.addBox(0F, 0F, 0F, 7, 10, 0);
        LeftBook.setRotationPoint(0F, 0F, 0F);
        LeftBook.setTextureSize(64, 32);
        LeftBook.mirror = true;
        setRotation(LeftBook, -0.0174533F, 0.0872665F, 0.1745329F);
        RightBook = new ModelRenderer(this, 15, 0);
        RightBook.addBox(0F, 0F, 0F, 7, 10, 0);
        RightBook.setRotationPoint(0F, 0F, 1F);
        RightBook.setTextureSize(64, 32);
        RightBook.mirror = true;
        setRotation(RightBook, 0.0174533F, -0.0872665F, 0.1745329F);

        Left_Wing = new ModelRenderer(this, 33, 0);
        Left_Wing.addBox(0F, 0F, 0F, 0, 8, 6);
        Left_Wing.setRotationPoint(2F, 3F, 1.3F);
        Left_Wing.setTextureSize(64, 32);
        Left_Wing.mirror = true;
        setRotation(Left_Wing, 1.570796F, 0F, 0.3490659F);

        Right_Wing = new ModelRenderer(this, 46, 0);
        Right_Wing.addBox(0F, 0F, 0F, 0, 8, 6);
        Right_Wing.setRotationPoint(2F, 3F, -0.3F);
        Right_Wing.setTextureSize(64, 32);
        Right_Wing.mirror = true;
        setRotation(Right_Wing, 1.570796F, -3.141593F, 0.3490659F);

        CenterBook = new ModelRenderer(this, 0, 11);
        CenterBook.addBox(0F, 0F, 0F, 6, 8, 1);
        CenterBook.setRotationPoint(0F, 1F, 0F);
        CenterBook.setTextureSize(64, 32);
        CenterBook.mirror = true;
        setRotation(CenterBook, 0F, 0F, 0.1745329F);
        BackBook = new ModelRenderer(this, 30, 0);
        BackBook.addBox(0F, 0F, 0F, 0, 10, 1);
        BackBook.setRotationPoint(0F, 0F, 0F);
        BackBook.setTextureSize(64, 32);
        BackBook.mirror = true;
        setRotation(BackBook, 0F, 0F, 0.1745329F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        LeftBook.render(f5);
        RightBook.render(f5);
        Left_Wing.render(f5);
        Right_Wing.render(f5);
        CenterBook.render(f5);
        BackBook.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        this.CenterBook.rotateAngleX = f5 / (float) Math.PI;
        this.Right_Wing.rotateAngleZ = MathHelper.cos(f3 * 1.1F) * (float) Math.PI * 0.25F;
        this.Left_Wing.rotateAngleZ = this.Right_Wing.rotateAngleZ;
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
